auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: zjfsdnu.github.io
url: http://zjfsdnu.github.io
feed: /atom.xml
author_info: <a href="http://zjfsdnu.github.io/">张金富</a>
